<a href="https://colab.research.google.com/github/SanjaraT/PyTorch-NN-Module/blob/main/NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Build Model
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
      super(Model, self).__init__()
      # neuron
      self.linear = nn.Linear(num_features, 1)
      # activation function
      self.sigmoid = nn.Sigmoid()

    def forward(self, features):
      x = self.linear(features)
      x = self.sigmoid(x)
      return x

In [2]:
# create dataset
features = torch.rand(10,5)
# model
model = Model(features.shape[1])
# forward pass
model(features)

tensor([[0.6345],
        [0.6264],
        [0.5648],
        [0.5881],
        [0.6020],
        [0.5900],
        [0.5803],
        [0.5908],
        [0.6115],
        [0.6273]], grad_fn=<SigmoidBackward0>)

In [3]:
model.linear.bias

Parameter containing:
tensor([0.1122], requires_grad=True)

In [4]:
!pip install torchinfo

In [5]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Neural Network with a Hidden Layer

In [33]:
class Model (nn.Module):
  def __init__(self, num_features):
    super(Model, self).__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [34]:
# create dataset
features = torch.rand(10,5)
# model
model = Model(features.shape[1])
# forward pass
model(features)

tensor([[0.5295],
        [0.5380],
        [0.5343],
        [0.5605],
        [0.5215],
        [0.5608],
        [0.5415],
        [0.5505],
        [0.5307],
        [0.5327]], grad_fn=<SigmoidBackward0>)

In [39]:
model.network[2].weight

Parameter containing:
tensor([[0.3298, 0.2435, 0.1662]], requires_grad=True)

In [40]:
model.network[2].bias

Parameter containing:
tensor([0.0338], requires_grad=True)

In [41]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00