<a href="https://colab.research.google.com/github/SanjaraT/PyTorch-NN-Module/blob/main/NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Build Model
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
      super(Model, self).__init__()
      # neuron
      self.linear = nn.Linear(num_features, 1)
      # activation function
      self.sigmoid = nn.Sigmoid()

    def forward(self, features):
      x = self.linear(features)
      x = self.sigmoid(x)
      return x

In [2]:
# create dataset
features = torch.rand(10,5)
# model
model = Model(features.shape[1])
# forward pass
model(features)

tensor([[0.6345],
        [0.6264],
        [0.5648],
        [0.5881],
        [0.6020],
        [0.5900],
        [0.5803],
        [0.5908],
        [0.6115],
        [0.6273]], grad_fn=<SigmoidBackward0>)

In [3]:
model.linear.bias

Parameter containing:
tensor([0.1122], requires_grad=True)

In [4]:
!pip install torchinfo

In [5]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Neural Network with a Hidden Layer

In [19]:
class Model (nn.Module):
  def __init__(self, num_features):
    super(Model, self).__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

In [20]:
# forward pass
def forward(self, features):
  out = self.linear1(features)
  out = self.relu(out)
  out = self.linear2(out)
  out = self.sigmoid(out)

  return out

In [21]:
# create dataset
features = torch.rand(10,5)
# model
model = Model(features.shape[1])
# forward pass
model(features)

tensor([[0.4806],
        [0.4489],
        [0.4806],
        [0.3965],
        [0.4806],
        [0.4806],
        [0.4657],
        [0.4679],
        [0.4806],
        [0.4806]], grad_fn=<SigmoidBackward0>)

In [22]:
model.linear1.weight

Parameter containing:
tensor([[-0.1351, -0.1981,  0.0624,  0.1875, -0.3118],
        [-0.2152,  0.1947, -0.3870,  0.1487, -0.4361],
        [-0.1856, -0.1279,  0.3579,  0.0248,  0.1945]], requires_grad=True)

In [23]:
model.linear1.bias

Parameter containing:
tensor([ 0.0396,  0.3805, -0.3850], requires_grad=True)

In [24]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00